# Generated by Django 3.2.20 on 2023-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=12233, max_length=20),
            preserve_default=False,
        ),
    ]
